apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeter-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeter-service
  template:
    metadata:
      labels:
        app: greeter-service
    spec:
      serviceAccountName: greeter-service-sa
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/zone
                operator: In
                values:
                - us-east-1d
      containers:
      - name: greeter-service
        image: adityahebballe/greeter-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"
        env:
        - name: ECHO_SERVICE_HOST
          value: "echo-service"
        - name: ECHO_SERVICE_PORT
          value: "8081"
        volumeMounts:
        - name: dummy-storage
          mountPath: "/app/data"
      volumes:
      - name: dummy-storage
        persistentVolumeClaim:
          claimName: dummy-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: greeter-service
spec:
  selector:
    app: greeter-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: greeter-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: greeter-service
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 50
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: greeter-service-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       greeter-service
  updatePolicy:
    updateMode: "Initial"
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: greeter-service-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: greeter-service