apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  DB_PASSWORD: "amFyLWRiLXBhc3MK" # base64 encoded "jar-db-pass"
  API_KEY: "amFyLWFwaS1rZXkK"       # base64 encoded "jar-api-key"
